name: demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.2
  provider: ^6.0.0
  firebase_auth: any
  firebase_core: any
  cloud_firestore: any
  flutter_blurhash: ^0.6.0
  flutter_localizations: 
    sdk: flutter
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 
  assets:  
    - assets/efinance.png
    - assets/appbarlogo.png
    - assets/background1.png
    - assets/background2.png
    - assets/background3.png
    - assets/background4.png
    - assets/viewbutton.png
    - assets/orderbutton.png
    - assets/addbutton.png