name: demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  provider: ^6.0.0
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_auth_web: ^5.9.9
  cloud_firestore: any
  flutter_blurhash: ^0.6.0
  flutter_localizations: 
    sdk: flutter
  intl: ^0.19.0
  image_picker: ^1.0.7
  image: ^4.1.3
  js: ^0.6.7
  image_picker_web: ^3.1.1
  http_parser: ^4.0.2
  universal_html: ^2.2.4
  dotted_border: ^2.1.0
  carousel_slider: ^4.2.1
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4
  flutter_time_picker_spinner: ^2.0.0
  geocoding: ^2.1.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 
  assets:  
    - assets/efinance.png
    - assets/appbarlogo.png
    - assets/background1.png
    - assets/background2.png
    - assets/background3.png
    - assets/background4.png
    - assets/viewbutton.png
    - assets/orderbutton.png
    - assets/addbutton.png
    - assets/credentials/cobalt-ion-442107-b8-f8666a191395.json
    - assets/entertainment.png
    - assets/events.png
    - assets/services.png
    - assets/visa.png
    - assets/taxi.png
    - assets/museums.png
    - assets/sharmlogo.png