// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY-LKEscZi-5dbHzyFDGnfjeKp203hY1Q',
    appId: '1:766208215140:web:7c3acd7c95f4c6f165f771',
    messagingSenderId: '766208215140',
    projectId: 'efinmerchclient',
    authDomain: 'efinmerchclient.firebaseapp.com',
    storageBucket: 'efinmerchclient.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW4BO71zTJAb-PsvN16d6SvXfSO087_TQ',
    appId: '1:766208215140:android:9efcc726501c583365f771',
    messagingSenderId: '766208215140',
    projectId: 'efinmerchclient',
    storageBucket: 'efinmerchclient.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8TzDMqQq6EE1xw3oniGcFeOrZFvpiReg',
    appId: '1:766208215140:ios:ed53387606e3a42965f771',
    messagingSenderId: '766208215140',
    projectId: 'efinmerchclient',
    storageBucket: 'efinmerchclient.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8TzDMqQq6EE1xw3oniGcFeOrZFvpiReg',
    appId: '1:766208215140:ios:ed53387606e3a42965f771',
    messagingSenderId: '766208215140',
    projectId: 'efinmerchclient',
    storageBucket: 'efinmerchclient.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY-LKEscZi-5dbHzyFDGnfjeKp203hY1Q',
    appId: '1:766208215140:web:de8755bedba5fe7c65f771',
    messagingSenderId: '766208215140',
    projectId: 'efinmerchclient',
    authDomain: 'efinmerchclient.firebaseapp.com',
    storageBucket: 'efinmerchclient.firebasestorage.app',
  );
}
